### PR TITLE
Upgrade to laravel 10 VEN-49

### PR DESCRIPTION
**Pull request by jamalla2**

### CODE REVIEW

**Review by HazemKhaled — CHANGES_REQUESTED** [review]
I believe you need to also update package.json to the latest laravel-mix

**Comment by jamalla2** [comment]
@HazemKhaled 
For the laravel-mix package, the current starter-kit uses laravel-mix 6.0.49, which is the latest version:
[npm: laravel-mix](https://www.npmjs.com/package/laravel-mix) 
[GitHub - laravel-mix/laravel-mix: The power of webpack, distilled for the rest of us.](https://github.com/laravel-mix/laravel-mix) 

However, according to Laravel 10 documentation, [Vite ](https://vitejs.dev/)has replaced Laravel Mix: 
[Laravel - The PHP Framework For Web Artisans](https://laravel.com/docs/10.x/mix) 



Shall i proceed with switching to Vite?

**Comment by jamalla2** [comment]
> I believe you need to also update package.json to the latest laravel-mix

For the laravel-mix package, the current starter-kit uses laravel-mix 6.0.49, which is the latest version:
[npm: laravel-mix](https://www.npmjs.com/package/laravel-mix) 
[GitHub - laravel-mix/laravel-mix: The power of webpack, distilled for the rest of us.](https://github.com/laravel-mix/laravel-mix) 

However, according to Laravel 10 documentation, [Vite ](https://vitejs.dev/)has replaced Laravel Mix: 
[Laravel - The PHP Framework For Web Artisans](https://laravel.com/docs/10.x/mix) 

 

Shall i proceed with switching to Vite?

**Review by HazemKhaled — APPROVED** [review]

**Comment by salkhwlani** [comment]
@jamalla2 yes please

**Comment by HazemKhaled** [comment]
@salahmyn Let's pause moving to Vit since we can't validate chunking bundles approaches are supported in microfrontend frameworks

**Pull request merged**
